import './pages/index.css';
import './images/image-03.png';
import './images/Facebook.png';
import './images/Git.png';
import './images/logout.png';
import './images/Rectangle 8.png';
import './images/Rectangle_active.png';
import './images/logout_black.png';
import './images/trash.png';
import './images/trash_inactive.png';
import './images/close.png';